# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rails_12factor', group: :production

gem "rake"
gem "sinatra"
gem "sinatra-contrib"
gem "twitter"
gem "curb"
gem "omniauth-twitter"
gem "oauth"


